In [33]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor

In [23]:
TRA = pd.read_csv('Data/Training_Data.csv')
PRE = pd.read_csv('Data/Prediction_Data.csv')

In [24]:
TRA

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Average_Laptime(s),Qualifying_Time(s),Starting_Pos,Race_Result
0,ALB,83.130,81.847,81.664,100.398929,80.941,15.0,12.0
1,ANT,81.376,79.943,80.324,95.665077,78.811,2.0,2.0
2,BEA,82.682,81.326,80.778,102.072750,80.311,12.0,7.0
3,BOR,81.696,81.668,80.459,99.549182,80.221,10.0,9.0
4,BOT,84.022,83.660,83.514,101.500360,83.244,19.0,19.0
...,...,...,...,...,...,...,...,...
56,PIA,91.865,90.133,90.364,105.411958,89.132,3.0,2.0
57,RUS,91.666,90.338,89.616,107.931045,89.076,2.0,4.0
58,SAI,93.383,91.608,91.829,105.217167,91.033,16.0,15.0
59,STR,95.294,93.951,93.485,114.290000,92.920,22.0,21.0
60,VER,92.457,91.509,90.910,103.802417,90.262,11.0,8.0

In [25]:
X = TRA.drop(['Race_Result','Driver'], axis=1)
y = TRA['Race_Result']

In [26]:
X

,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Average_Laptime(s),Qualifying_Time(s),Starting_Pos
0,83.130,81.847,81.664,100.398929,80.941,15.0
1,81.376,79.943,80.324,95.665077,78.811,2.0
2,82.682,81.326,80.778,102.072750,80.311,12.0
3,81.696,81.668,80.459,99.549182,80.221,10.0
4,84.022,83.660,83.514,101.500360,83.244,19.0
...,...,...,...,...,...,...
56,91.865,90.133,90.364,105.411958,89.132,3.0
57,91.666,90.338,89.616,107.931045,89.076,2.0
58,93.383,91.608,91.829,105.217167,91.033,16.0
59,95.294,93.951,93.485,114.290000,92.920,22.0
60,92.457,91.509,90.910,103.802417,90.262,11.0

In [27]:
y

0     12.0
1      2.0
2      7.0
3      9.0
4     19.0
      ...
56     2.0
57     4.0
58    15.0
59    21.0
60     8.0
Name: Race_Result, Length: 61, dtype: float64

In [28]:
model = Ridge()

In [29]:
params = {'alpha': [0.1, 1.0, 10.0],
        'solver': ['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga'],
        'max_iter': [1000, 5000, 10000]
        }

In [30]:
grid = GridSearchCV(
    estimator=Ridge(),
    param_grid=params,
    cv=5,
    scoring='neg_mean_absolute_error'
)

In [31]:
grid.fit(X, y)

print(grid.best_params_)
print(grid.best_score_)

{'alpha': 10.0, 'max_iter': 10000, 'solver': 'saga'}
-4.223158531897518

In [45]:
grid1 = GridSearchCV(
    estimator=RandomForestRegressor(),
    param_grid={
        'n_estimators': [50, 100,150, 200,250],
        'max_depth': [3, 5, 10]
    },
    cv=5,
    scoring='neg_mean_absolute_error'
)

In [46]:
grid1.fit(X, y)

print(grid1.best_params_)
print(grid1.best_score_)

y_pred = grid.predict(X)

{'max_depth': 3, 'n_estimators': 50}
-3.681596201762204

In [47]:
from scipy.stats import spearmanr
rho, p_value = spearmanr(y, y_pred)

In [48]:
rho

np.float64(0.6846823990421448)

In [49]:
import joblib
joblib.dump(grid1, 'Model/RandomForestModel1.pkl')

['Model/RandomForestModel1.pkl']

In [ ]:
print